onlyBuiltDependencies:
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - sharp
  - tesseract.js
blockExoticSubdeps: false
overrides:
  path: ^0.12.7
allowBuilds:
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  tesseract.js: true
